### PR TITLE
net5/6 support

### PR DESCRIPTION
**Pull request by haraldsteinlechner**
- switched from fake-cli to vanilla dotnet fsi
- added net5.0/net6.0 target for the tool https://github.com/krauthaufen/Adaptify/issues/17

### CODE REVIEW

**Comment by haraldsteinlechner** [comment]
@krauthaufen should we merge this one?

**Comment by krauthaufen** [comment]
Yep, why not?
Why do we need all the fsx things under version control?

**Comment by krauthaufen** [comment]
We could simply generate them in build.cmd/sh right?

**Comment by haraldsteinlechner** [comment]
i just cleaned it up (forcefully ;)) - also .config was missing

**Pull request merged**
